---
title: "On Learning Math"
date: 2026-06-28
description: "Some thoughts on good habits for learning math well."
categories: [math, education]
---


**For Final Version**
- Originally for my brother who wanted advice on spending less time doing math homework. This is a guide for ACME students who are wondering how people do ACME and enjoy life. I wrote it as someone who really floundered (lifestyle-wise) in the pre-reqs and during junior core, but who found my stride during Senior year. I don't do homework after 6pm and rarely on weekends. 
- Aims to teach general but practical principles. Will be useful for any class.
- Nod to deep work.
- This lays out good *habits*. All about consistency, little things each day. Important to not get in your own way--don't tell yourself "But I'm not a good student". Success in ACME is not about being a gifted or smart mathematician. It's about being consistent and diligent. So tell yourself not that you are smart but that you are dedicated and consistent, and then give yourself evidence that that is true.

I originally wrote this for my brother Logan who followed me into the applied math major at BYU a few years after I started. He quickly felt bogged down by the workload and asked advice on spending less time doing math homework. I ended up trying to distill everything I had learned and observed about how to do BYU's ACME program *and* enjoy life. I wrote it as someone who really floundered (lifestyle-wise) during the pre-reqs and during the first year of the program, but who found my stride during Senior year. I never did homework after 6pm and rarely on weekends, and did better than ever in class and on tests.

I aim to communicate general but practical principles. They will likely be useful for any class. 

This guide advises good *habits*--practices that require consistency, little efforts each day. I also think it is important to not get in your own way--don't tell yourself "But I'm not a good student". Success in math (or anywhere) is not about being a gifted or smart mathematician. It's about being consistent and diligent. So tell yourself not that you are smart but that you are dedicated and consistent, and then give yourself evidence that that is true.

---

I know you asked specifically about spending less time, but as I wrote this I realized I was also talking about effectively learning math. 

The best way to spend less time on math homework is to not do it. While that's quite straightforward, it's not very satisfactory. The real goal is to spend the least amount of time possible on math homework while still clearing some minimum standard of math understanding and, of course, a minimum grade. I imagine your standard for minimum grade is pretty high and your standard for math understanding should be pretty high too. So, then, you only want to engage in activities that efficiently get you to homework completion and math understanding in as little time as possible. 

Remember that you may spend a bit of frustrating, seemingly inefficient time on the way to deep, satisfying insight. There are good ways to decrease frustrated time but I don't think there is a way to deep insight without any at all. 

Here goes.

# A new approach to learning math
You may have already made this switch--I just know it took me longer than it should have. I know we have already talked about it too, but I want to hit it again. There was a big shift for me, in between high school and university, away from learning a formulaic approach to math to learning a relational one. Let me explain in terms of being bad at directions.

For much of my life, I haven't been great at directions. I wasn't interested in getting a feel for the city I grew up in, I just wanted to get from point A to point B, and 90% of the time A and B where our house, North High School, church, a few friends' houses, or Culver's. I was able to learn directions as a linear series of turns: "Turn right on Superior Ave, left at the first intersection, right by the Sport's Core sign" or "Left onto Superior, left at the big intersection, right on North, left on before the cemetery". This worked just fine for me, especially when I could use google maps easily when I didn't know how to get to *that* Culver's or to a house I hadn't visited before.

My series to get to the Sheboygan Youth Sailing Center is "Left on Superior, keep going, keep going, right on third", even though I knew it wasn't the best way to get there. When I was in Sheboygan a few months ago, I decided to take Erie. I knew how to get to Erie--"right at the round about, right on after the movie theater, left onto the ramp"--but once I was on it I had no idea when to turn. I didn't know where I was and I didn't know where other places were, because I had left one of my linear series of turns. My brother Truman had to guide me step by step. Funny enough, he messed up and had me turn earlier than he usually does, but he was unfazed because he still knew where he was and got me to the sailing center easily. 

Truman (and Jack Allen and maybe you) doesn't think of Sheboygan like a subway line, with discrete tracks in between places of interest. It's a bunch of places that are all related to each other by direction and distance. If he knows where he is, he knows where everything else is. Rather than thinking about directions like formulas, he thinks about the map.

It is lazier, less useful, and less sticky to learn directions linearly rather than becoming familiar with the city itself. Similarly, learning math by memorizing formulas or the wording of theorems is lazy, hard to apply, and hard to remember. Many people don't know there is another way, so they unavoidably hate math. 

It is drudgery to memorize the eleven properties of a full-rank matrix. It would take a lot of flashcard reps to recall that "full rank square matrix "is equivalent to 
	- Column space spans the whole vector space
	- Row space spans the whole vector space
	- Invertible
	- Diagonalizable
	- Determinant $\neq$ 0
	- Nonzero eigenvalues
	 ...
And the list goes on! The Jackson of math nonetheless trudges forward and works to drill into his head that these all go together. The Trumans think about it in terms of relationships and ask *why* a determinant of zero should mean a matrix isn't invertible. Grant Sanderson does a great job making this clear. 

>Since a determinant is the factor by which the area of shape changes under the matrix transformation, a determinant of zero would mean the space gets squashed into a lower dimension, which necessarily means lots of points get mapped to the same point under the transformation--so starting with a transformed point, you can't go backwards. Makes sense.

When that is in place and makes sense, the explanation of eigenvalues as "magical values such that $A\vec{x} = \lambda \vec{x}$" won't be enough. You'll dig and ask why until you arrive somewhere like, 

> The transformation denoted by matrix $A$ can be decomposed into eigenvectors with associated eigenvalues--and if an eigenvalue is 0, that means there is squashing in the direction of that eigenvector. So it's the squashing thing again.

You will see that "$A$ is invertible" isn't just a package deal with "$det(A) \neq 0$", they are just two different ways to say the same thing--that $A$ doesn't squash dimensions down, so you can work backwards. Proofs will change from complex recipes to windows into the fundamental nature of things. Good proofs teach you more about the objects that show up in the proof.

Then on homework and exams, you won't get lost after a few unexpected turns. And when you find yourself in uncharted territory, you'll have the skills to make a map. You'll be a mathematician. So be a Truman. 

The rest of this is more or less ways to learn math in this way, and common pitfalls to avoid.

# I. Think hard
>Memory is the residue of thought.
>~Daniel Willingham

Learning, in any discipline, is the result of actively engaging with the material to be learned. Thinking hard is what digs the grooves through which thought can flow. An apt analogy is that of lifting weights. Looking at weights or reading about lifting weights or enlisting a friend or robot to lift weights for you can't make you stronger. You need to do the heavy lifting! Likewise, in order to learn math (or anything), you need to think about it hard.

Some practical examples--which we will go over in more detail--are exercises like working through examples on your own, summarizing or explaining sections and proofs, and giving homework sets real concentrated effort.

**This section is relevant always, but especially during test season.**

### 1. Studying in a way that promotes thinking hard
Flashcards are fine. It is the most minimal way to spend time thinking about the content. There is a strong recall aspect to math, most obviously for things like definitions and formulas. However, flashcards can sell you short. Thinking about "Why is this definition useful? Why would we want to set aside something with these properties?" or "What is this formula really saying and why is it set up that way?" is much better than rote memorization. Flashcards that prompt you to think about the connections and motivations of the content you are reviewing will be best.

> *Practice*: On definition cards, ask yourself, "What is the benefit of this definition and what role do the parts of definition play in theorems?" Include examples and tricky unexamples of the definition.

> *Practice*: For theorems, drill the statement, but also ask "What is this really saying and how is it used? What situations does it simplify?" Likewise, know examples of when it can be applied and tricky unexamples. See if you can't talk through a hand-wavey proof that amounts to "What is this really saying and why is true?"

Better than flashcards is to create a thread of reasoning through entire chapters, creating the logical succession of topics yourself. "Why do we care about this concept, what questions does it answer, when is it useful, why should I care, how does the proof work?" Explaining things in your own words is hard work, and excellent for learning.

Proofs in particular are an important way to engage deeply with math. Good proofs teach the student something fundamental about the mathematical objects involved. When studying proofs, ask "What fundamental truths does this proof teach me?" In some classes (Math 290 and Math 341), your teacher will have you memorize a certain few proofs. Again, I find it is good to have a hand-wavey explanation for almost every proof. You should have some intuition for nearly every one. The exception is when the book skips it because it's too technical or when your teacher says, "This is a pointless,  uninstructive proof," as will sometimes happen.

This intuition snowballs quickly. A willingness to put in the work to understand proofs today will make it much easier to learn proofs that build on the foundation in the future. On the other hand, it requires a lot of time to just barely re-learn the proofs again and again, remedially--it's a kind of debt that becomes difficult to pay off.
## 2. Review often
It is best to spread the hard thinking out. Inevitably, you will have upticks in the days before midterms and finals. The best case is if you can spread it thin so you are spending just 10-15 minutes a day reviewing past material, and hours less during exam weeks. This will give you a surprisingly big edge in class and on homework, where you will start piecing things earlier than if you cram. Things will seem easier. Homework will go faster. 

In the past, my major insights and connections came to me during exam weeks, because that was when I spent the time going over all the material. It's when I set myself up to make connections. If you review earlier, in small bites, you'll make those connections throughout the semester and be faster throughout.

Go at it with the idea of "I will review more per day but the area under the curve will be the same", but in practice I think the total time spent studying and doing homework will decrease substantially.

Again, great further reading in Tyler Jarvis' [How Not To Study](https://mathdept.byu.edu/~jarvis/AdviceForStudents/HowNotToStudy.pdf)--what not to do.
## II. Prepare for class
Nearly every teacher advises students to prepare well for class, and nearly every student skimps on it. It's easy to bounce between the next thing due for other classes and either skip the reading or blasting through it to take a reading quiz. Don't fall for this. Consider Terry Pratchett's "boot theory" of economics:

>The reason that the rich were so rich, Vimes reasoned, was because they managed to spend less money. Take boots, for example. ... A really good pair of leather boots cost fifty dollars. But an affordable pair of boots, which were sort of OK for a season or two and then leaked like hell when the cardboard gave out, cost about ten dollars. ... But the thing was that good boots lasted for years and years. A man who could afford fifty dollars had a pair of boots that'd still be keeping his feet dry in ten years' time, while a poor man who could only afford cheap boots would have spent a hundred dollars on boots in the same time and _would still have wet feet_.   
>
This was the Captain Samuel Vimes 'Boots' theory of socio-economic unfairness.[^pratchett]

When you rush and always complete everything right before it is due, you are buying a cheap set of boots. This only requires you to spend more time later to understand how to do the associated homework and read and re-read the textbook, or spend time with a TA or your professor. Buy the nice pair of boots by taking time to really do the reading and work to understand it. This will mean you spend less time later--and less time overall--to achieve understanding, complete homework efficiently, and perform well on tests.
### 1. Do the reading before class

>*Practice*: Read the textbook with your notes out. Don't copy down the template of the section, but write down what seems important. I write the most explaining the things I understand the least and it is *magic* the way the pieces fit together as I do so. I often start a sentence not knowing how I'll finish it, only to have it all click together before I finish. And then I get it! 
>Working to explain the tricky stuff is an *incredible* exercise for your brain.

Working hard to understand the reading will equip you to make the most of the corresponding lecture. You will ask the relevant questions because you will know where you got stuck, and which parts you know you actually don't get--the things that you would have thought, "yeah I could figure that out" had you merely glanced through the reading. The lecture will solidify your learning rather than introduce it.

A fantastic deeper resource on this point is from Tyler Jarvis, [How To Read A Math Book](https://mathdept.byu.edu/~jarvis/AdviceForStudents/HowToReadAMathBook.pdf)
### 2. Give the homework a first pass
This is the practice that has made the most surprising difference for me. Giving the homework an earnest, focused first pass locks in the content from the reading through practice, and exposes weak spots in understanding.

The first pass has its own set of rules. Just go for each problem until you know exactly how to solve the rest (maybe leave yourself a note), or until you're stuck. If you get stuck, it's a good idea to note exactly what is stopping you. Don't give up too easily. The time you spend checking with the section for how to proceed is vital. Don't push forward too hard either, it's just a first pass. For sure don't spend more than ten minutes or so a problem.

### 3. Plan out a schedule to implement these
These two key preparations changed the game. Not only am I perpetually "ahead" in class and never worried about the due-dates, but I get so much more out of class time. Things make more sense so it's easier to pay attention, and I ask the questions I need to. Furthermore I have done *much* better on exams. And I have spent less time while enjoying myself more!

This may require that you spend a weekend or a few evenings working extra to get ahead of where you are now. It is a million times worth it.

# III Limit time spent doing math
There is a universal law of life that every math student must learn.

> \[Math homework\] will fill the amount of time you make available to it.

When you sit down and day, "Well I have until \[time] to finish this", be it an encouraging amount of time or a discouraging amount of time, you will take that amount of time to finish it. Almost always. I'm not certain why this is--maybe because we go slower because we know we can, or put an extra finish on each problem if there's time, or urgency makes our brain work better. 

I just know that even if I hustle, it will take me right to the edge of my available time slot to finish what I am working on.

The solution to this is to 1) give yourself less time and 2) have lower standards for what is good enough.
## 1. Non-negotiable schedule
The most important way to constrain the time you spend doing math is by blocking off non-negotiable events. 

Set a stop-time later than which you will not do homework. I recommend that it be much earlier than your bedtime. I stop at 6pm. Whether you're done or not doesn't matter, no homework past stop-time.

Schedule consistent times to exercise. Exercise at midday is better than exercise in the morning is better than exercise at night, is what I have found. Fun exercise is always the best.

This is hard to do initially but it *rewires* your brain. You will likely be surprised that you continue to get just as many things done in less time. You will also have more time to do the things you want to do, like spend time with friends/family or on your own hobbies. Not least is the fact that sleeping enough, exercising, and getting good social connection time is another way to buy the nice pair of boots and keep the saw sharp. These three things are part of being a healthy and happy person, and certainly don't hurt your math education.

## 2. The 80% rule
The 80% is as follows:

>You should always be willing to stop at 80%.

80% is enough--if you have given your best effort, worked to understand, talked to a TA, and it still isn't coming along, don't finish it. Leave it be. This is *by problem*, not by problem set. Doing just 80% of five problems each is a valiant effort and suffices. 100% of four out of five problems does not.

This also isn't a *reason* to stop at 80%. You should always shoot for 100%. However, if you are already spinning your wheels, have checked in with helpful resources, or just don't have time, 80% is a reasonable minimum standard.

This is partly the law of diminishing returns--a continued effort just isn't worth the time and distress it causes for the understanding or points gained. In my experience, 80% of the problem generally earns more than 80% of the points anyway.

>*Practice*: The 80% rule pairs well with the first pass. I will often do the first pass, and leave some problems undone, awaiting office hours, TA hours, or to ask other students. I will usually work on my homework for up to an hour total after the first pass--and turn in whatever is done at that point. The time gained is extra time for the more important things in my life, and for review.

Leaving things undone on purpose like this can be difficult, especially when you're leaving it undone in order to spend time with friends or to get to bed early. It is very worth it, and if it isn't too difficult to leave homework 20% undone, then your priorities are in the right place.

An extra note--this is for problem sets assigned for homework. The same is not true when reviewing, studying for exams, or taking exams. Give 100% there.
## 3. Using resources: TAs and office hours
You would be silly not to use all of the resources available to help you learn math. The challenge is to spend time efficiently with these resources, which means maximizing understanding gained per minute. 

The number one best way to make the most of these resources on your way to math understanding is to give each problem your best shot before phoning a friend. Firstly, this will prevent these helps from becoming a crutch or a shortcut that hinder your full understanding. Secondly, it will make your time spent in office hours or with friends targeted more exactly on the source of your question or problem, rather than spending your time and a TA's time working through something you could do on your own, and missing out on your own discovery. It is hard to overestimate the power of precisely identifying the thing you don't understand. What step of the proof? What point in the computation? Very often, a careful formulation of the question is all it takes to figure out the solution.

The following are just a few additional tips for each resource, but the main principle is the above paragraph.

**TAs**
Math TAs, in my experience, are cheerful, helpful, and patient. However, like anybody, they can sometimes get impatient and just sketch out each step of the problem at hand. They may think that's what you want and that they are doing you a favor. It isn't and they're not. It pays to frame your request carefully: "Could you point me in the right direction...", "I'm having trouble getting started. Is there a trick or a theorem in the book I'm supposed to be using?" and similar requests can get you the help you need without short-changing your learning. It may also pay to identify some TAs you like, that explain concepts in a way that jive with you, and stick to them.

**Office hours**
Go to office hours. Some professors really can address more foundational understanding and often give bigger perspectives than TAs. Some don't. It's worth figuring out.

Giving the problem your best shot and formulating your precise question is likely most important here, not just so you don't waste a professor's time, but also so they like you more. This is important for letters of recommendation when applying for internships, jobs, or grad school. Creating a genuine relationship with professors is also a way to become friends with kind, interesting, knowledgeable people that can be important mentors to you for your entire life.

**Study groups**
Study groups are tricky. The overarching principle still applies, but a little differently. Presumably, the members of your study group don't know the answers like your professor or your TA. Give the problem some thought on your own, whether that's while you're with the group or before, and then brainstorm together on how to continue. If you figure it out first, be careful to not be a bad TA--people don't always like it when you lay out your solution unsolicited. Likewise, don't let another group member become a crutch for you.

>*Practice*: Personally, I prefer to have sketched out each problem as far as I can before starting to work with others. Then I can check the problems I finished to see if others did them the same, or I can ask, "How did you approach this step?" And by then I have thought enough about the problem to be able to talk about it.

It's a challenge to work effectively with a group, but it is worth learning! A key part of your undergraduate education should be how to collaborate on math problems.


[^pratchett]: Pratchett, Terry (1993). _Men at Arms_. London: Gollancz. p. 32. ISBN 0-575-05503-0. OCLC 29470107


